name: CD

on:
  push:
    branches:
      - main

jobs:
  gcr-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: GCP Authenticate
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    - name: Configure docker
      run: gcloud auth configure-docker --quiet
    - name: Build
      run: docker build -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:$GITHUB_SHA -t asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend:latest -f ./.docker/Dockerfile.prod .
    - name: Push
      run: docker push asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/frontend --all-tags
